---
- hosts: all
  roles:
    - { role: "core", tags: "core" }
    - { role: "vscode", tags: "vscode" }
    - { role: "javascript", tags: "javascript" }
    - { role: "i3", tags: "i3" }
    - { role: "study", tags: "study" }
    - { role: "python", tags: "python" }
    - { role: "office", tags: "office" }
    - { role: "cloud", tags: "cloud" }
    - { role: "media", tags: "media" }
  vars:
    - user_home_path: "/home/tristan/"
    - default_user: "tristan"
  become: true
  become_user: "tristan"
