---
- name: Set up the Microsoft Apt signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: Set up the Microsoft repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
- name: Install VSCode
  apt:
    name: code
    update_cache: true
