---
- name: Set up the Microsoft Apt signing key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: Set up the Microsoft repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
- name: Install VSCode
  apt:
    name: code
    update_cache: true
- name: Copy settings file
  copy:
    src: settings.json
    dest: "{{ user_home_path }}.config/Code/User/settings.json"
- name: Install generally useful extensions
  become: true
  become_user: "{{ default_user }}"
  shell: code --install-extension esbenp.prettier-vscode