---
- name: Install essential build tools
  become: true
  become_user: root
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - build-essential
      - clang
      - git
      - curl
      - python3-distutils

- name: Install other command line utilities
  become: true
  become_user: root
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - htop
      - tree

- name: Update the number of file watches
  become: true
  become_user: root
  lineinfile:
    path: /etc/sysctl.conf
    line: fs.inotify.max_user_watches=524288

- name: Install zsh
  become: true
  become_user: root
  apt:
    name: zsh
    update_cache: true

- name: Install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ user_home_path }}.oh-my-zsh"

- name: Copy .zshrc
  copy:
    src: .zshrc
    dest: "{{ user_home_path }}.zshrc"

- name: Set default shell
  become: true
  become_user: root
  user:
    name: "{{ default_user }}"
    shell: /bin/zsh

- name: Download Google Chrome deb
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome.deb

- name: Install Google Chrome
  become: true
  become_user: root
  apt:
    deb: /tmp/google-chrome.deb

- name: Install postman for REST development
  become: true
  become_user: root
  snap:
    name: postman
