---
- name: Install essential build tools
  become: true
  become_user: root
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - build-essential
      - git
      - curl
      - python3-distutils

- name: Install other command line utilities
  become: true
  become_user: root
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - htop
