---
- name: Install essential build tools
  become: true
  become_user: root
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - build-essential
      - clang
      - git
      - curl
      - python3-distutils

- name: Install other command line utilities
  become: true
  become_user: root
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - htop

- name: Update the number of file watches
  become: true
  become_user: root
  lineinfile:
    path: /etc/sysctl.conf
    line: fs.inotify.max_user_watches=524288