---
- name: Install python3 deps
  become_user: root
  become: true
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - python3-venv
      - python3-dev
- name: Install some common django deps
  become_user: root
  become: true
  apt:
    name: libpq-dev
    update_cache: true
