---
- name: Install ruby
  become_user: root
  become: true
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
      - ruby-full
      - zlib1g-dev # For some gems
      - redis-server # For some development
      - postgresql # For servers
      - postgresql-contrib
- name: Install bundler
  gem:
    name: bundler
    state: present
